EasyLoader: Wing.Tools.EaseLoader.ReferenceObject Class Reference
Wing.Tools.EaseLoader.ReferenceObject Class Reference
Public Member Functions
ReferenceObject (string _key, object _data=null)
void Ref ()
when use this data,please invoke this. this function will add refrence count. when count equal to 0,this data maybe collected.
void Refresh ()
just refresh hit time
void UnRef ()
when unuse this data,please invoke this. this function will minus one time from refrence count. when count equal to 0,this data maybe collected.
virtual void Dispose (bool unloadedLoadedObject=false)
focus to dispose this data,maybe dispose the using data.
Parameters
unloadedLoadedObject Determines whether the current instances of objects loaded from the AssetBundle will also be unloaded.
Properties
string key [get]
ReferenceObject parent [get, set]
List< ReferenceObject > childrens [get]
int referenceCount [get]
bool used [get]
float hitTime [get]
object data [get, set]
Constructor & Destructor Documentation
ReferenceObject()
Wing.Tools.EaseLoader.ReferenceObject.ReferenceObject (string _key, object _data = null)
References Wing.Tools.EaseLoader.ReferenceObject.data, and Wing.Tools.EaseLoader.ReferenceObject.key.
Member Function Documentation
Dispose()
virtual void Wing.Tools.EaseLoader.ReferenceObject.Dispose (bool unloadedLoadedObject = false) virtual
focus to dispose this data,maybe dispose the using data.
Parameters
unloadedLoadedObject Determines whether the current instances of objects loaded from the AssetBundle will also be unloaded.
References Wing.Tools.EaseLoader.AssetBundle, Wing.Tools.EaseLoader.AudioClip, and Wing.Tools.EaseLoader.ReferenceObject.data.
Ref()
void Wing.Tools.EaseLoader.ReferenceObject.Ref ()
when use this data,please invoke this. this function will add refrence count. when count equal to 0,this data maybe collected.
References Wing.Tools.EaseLoader.ReferenceObject.parent, Wing.Tools.EaseLoader.ReferenceObject.Ref(), and Wing.Tools.EaseLoader.ReferenceObject.Refresh().
Refresh()
void Wing.Tools.EaseLoader.ReferenceObject.Refresh ()
just refresh hit time
UnRef()
void Wing.Tools.EaseLoader.ReferenceObject.UnRef ()
when unuse this data,please invoke this. this function will minus one time from refrence count. when count equal to 0,this data maybe collected.
References Wing.Tools.EaseLoader.ReferenceObject.parent, and Wing.Tools.EaseLoader.ReferenceObject.UnRef().
Property Documentation
childrens
List<ReferenceObject> Wing.Tools.EaseLoader.ReferenceObject.childrens get
data
object Wing.Tools.EaseLoader.ReferenceObject.data get set
hitTime
float Wing.Tools.EaseLoader.ReferenceObject.hitTime get
key
string Wing.Tools.EaseLoader.ReferenceObject.key get
parent
ReferenceObject Wing.Tools.EaseLoader.ReferenceObject.parent get set
referenceCount
int Wing.Tools.EaseLoader.ReferenceObject.referenceCount get
used
bool Wing.Tools.EaseLoader.ReferenceObject.used get
The documentation for this class was generated from the following file:
EaseLoader/Scripts/Msic/ResponseData.cs