EasyLoader: Wing.Tools.EaseLoader.LoaderManager Class Reference
Wing.Tools.EaseLoader.LoaderManager Class Reference
Classes
class CancelInfo
Public Member Functions
LoaderManager ()
void Regist (string type, ILoader loader, Type paramterType)
ILoader GetLoader (LoadContext context)
void KillAll (bool triggerCompleted=false)
void Kill (object context, bool triggerCompleted=false)
stop load (useless in async mode)
LoadContext CreateContext (string url, EResourceType resourceType, Type assetType=null)
LoadContext Load (string url, Type assetType, LoadProgressEventHandler progress=null, LoadCompletedEventHandler completed=null, Dictionary< string, object > extraParams=null, object tag=null, LoaderTrigger trigger=null)
LoadContext SimpleLoad (string url, EResourceType resourceType, LoadProgressEventHandler progress=null, LoadCompletedEventHandler completed=null, ECacheType cacheType=ECacheType.None, object tag=null, LoaderTrigger trigger=null)
LoadContext Load (string url, EResourceType resourceType, LoadProgressEventHandler progress=null, LoadCompletedEventHandler completed=null, Dictionary< string, object > extraParams=null, object tag=null, LoaderTrigger trigger=null)
bool IsLoading (LoadContext context)
LoadContext Load (LoadContext context, LoaderTrigger trigger=null)
LoadContext[] Load (LoadItem[] reqs, Action< float > onProgress=null, LoadCompletedEventHandler onItemCompleted=null, Action< ResponseData[]> allCompleted=null, bool sequence=false, LoaderTrigger trigger=null)
IEnumerator Load (LoadContext[] ctxs, Action< float > onProgress, LoadCompletedEventHandler onItemCompleted=null, Action< ResponseData[]> allCompleted=null, bool sequence=false)
ResponseData LoadSync (string url, Type assetType, Dictionary< string, object > extraParams=null, object tag=null, CancellationToken cancellationToken=default(CancellationToken))
ResponseData LoadSync (string url, EResourceType resourceType, Dictionary< string, object > extraParams=null, object tag=null)
ResponseData SimpleLoadSync (string url, EResourceType resourceType, ECacheType cacheType=ECacheType.None, object tag=null)
ResponseData LoadSync (LoadContext context, CancellationToken cancellationToken=default(CancellationToken))
ResponseData[] LoadSync (LoadItem[] reqs, Action< float > onProgress=null, LoadCompletedEventHandler onItemCompleted=null)
Public Member Functions inherited from Wing.Tools.MonoSingleton< LoaderManager >
virtual void Initial ()
Properties
TaskLimiter Limiter [get]
Properties inherited from Wing.Tools.MonoSingleton< LoaderManager >
static T Instance [get]
Additional Inherited Members
Static Protected Attributes inherited from Wing.Tools.MonoSingleton< LoaderManager >
static bool s_bEnableAutoCreate
static T s_pInstance
Constructor & Destructor Documentation
LoaderManager()
Wing.Tools.EaseLoader.LoaderManager.LoaderManager ()
References Wing.Tools.EaseLoader.EditorLoader.name, Wing.Tools.EaseLoader.ResourceLoader.name, Wing.Tools.EaseLoader.RuntimeLoader.name, Wing.Tools.EaseLoader.WebLoader.name, and Wing.Tools.EaseLoader.LoaderManager.Regist().
Member Function Documentation
CreateContext()
LoadContext Wing.Tools.EaseLoader.LoaderManager.CreateContext (string url, EResourceType resourceType, Type assetType = null)
References Wing.Tools.NormalSingleton< T >.Instance.
GetLoader()
ILoader Wing.Tools.EaseLoader.LoaderManager.GetLoader (LoadContext context)
IsLoading()
bool Wing.Tools.EaseLoader.LoaderManager.IsLoading (LoadContext context)
References Wing.Tools.EaseLoader.LoadContext.key.
Kill()
void Wing.Tools.EaseLoader.LoaderManager.Kill (object context, bool triggerCompleted = false)
stop load (useless in async mode)
Parameters
context
triggerCompleted
KillAll()
void Wing.Tools.EaseLoader.LoaderManager.KillAll (bool triggerCompleted = false)
References Wing.Tools.MonoSingleton< LoaderManager >.Instance, Wing.Tools.EaseLoader.LoaderManager.Kill(), and Wing.Tools.EaseLoader.TaskLimiter.RemoveAll().
Load() [1/5]
LoadContext Wing.Tools.EaseLoader.LoaderManager.Load (LoadContext context, LoaderTrigger trigger = null)
References Wing.Tools.EaseLoader.LoadContext.trigger.
Load() [2/5]
IEnumerator Wing.Tools.EaseLoader.LoaderManager.Load (LoadContext[] ctxs, Action< float > onProgress, LoadCompletedEventHandler onItemCompleted = null, Action< ResponseData[]> allCompleted = null, bool sequence = false)
References Wing.Tools.EaseLoader.LoadCompletedEventHandler(), Wing.Tools.EaseLoader.LoadProgressEventHandler(), and Wing.Tools.EaseLoader.LoadContext.onProgress.
Load() [3/5]
LoadContext[] Wing.Tools.EaseLoader.LoaderManager.Load (LoadItem[] reqs, Action< float > onProgress = null, LoadCompletedEventHandler onItemCompleted = null, Action< ResponseData[]> allCompleted = null, bool sequence = false, LoaderTrigger trigger = null)
References Wing.Tools.EaseLoader.LoaderManager.CreateContext(), and Wing.Tools.EaseLoader.LoaderManager.Load().
Load() [4/5]
LoadContext Wing.Tools.EaseLoader.LoaderManager.Load (string url, EResourceType resourceType, LoadProgressEventHandler progress = null, LoadCompletedEventHandler completed = null, Dictionary< string, object > extraParams = null, object tag = null, LoaderTrigger trigger = null)
References Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.Load().
Load() [5/5]
LoadContext Wing.Tools.EaseLoader.LoaderManager.Load (string url, Type assetType, LoadProgressEventHandler progress = null, LoadCompletedEventHandler completed = null, Dictionary< string, object > extraParams = null, object tag = null, LoaderTrigger trigger = null)
References Wing.Tools.EaseLoader.Utils.ConvertResourceType(), Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.Load().
LoadSync() [1/4]
ResponseData Wing.Tools.EaseLoader.LoaderManager.LoadSync (LoadContext context, CancellationToken cancellationToken = default(CancellationToken))
References Wing.Tools.EaseLoader.DefaultSettings.showDebugInfo.
LoadSync() [2/4]
ResponseData[] Wing.Tools.EaseLoader.LoaderManager.LoadSync (LoadItem[] reqs, Action< float > onProgress = null, LoadCompletedEventHandler onItemCompleted = null)
References Wing.Tools.EaseLoader.LoaderManager.CreateContext(), and Wing.Tools.EaseLoader.LoaderManager.LoadSync().
LoadSync() [3/4]
ResponseData Wing.Tools.EaseLoader.LoaderManager.LoadSync (string url, EResourceType resourceType, Dictionary< string, object > extraParams = null, object tag = null)
References Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.LoadSync().
LoadSync() [4/4]
ResponseData Wing.Tools.EaseLoader.LoaderManager.LoadSync (string url, Type assetType, Dictionary< string, object > extraParams = null, object tag = null, CancellationToken cancellationToken = default(CancellationToken))
References Wing.Tools.EaseLoader.Utils.ConvertResourceType(), Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.LoadSync().
Regist()
void Wing.Tools.EaseLoader.LoaderManager.Regist (string type, ILoader loader, Type paramterType)
References Wing.Tools.EaseLoader.ILoader.onCompleted, and Wing.Tools.EaseLoader.ILoader.onProgress.
SimpleLoad()
LoadContext Wing.Tools.EaseLoader.LoaderManager.SimpleLoad (string url, EResourceType resourceType, LoadProgressEventHandler progress = null, LoadCompletedEventHandler completed = null, ECacheType cacheType = ECacheType.None, object tag = null, LoaderTrigger trigger = null)
References Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.Load().
SimpleLoadSync()
ResponseData Wing.Tools.EaseLoader.LoaderManager.SimpleLoadSync (string url, EResourceType resourceType, ECacheType cacheType = ECacheType.None, object tag = null)
References Wing.Tools.NormalSingleton< T >.Instance, and Wing.Tools.EaseLoader.LoaderManager.LoadSync().
Property Documentation
Limiter
TaskLimiter Wing.Tools.EaseLoader.LoaderManager.Limiter get
The documentation for this class was generated from the following files:
EaseLoader/Scripts/Loader/LoaderManager.cs
EaseLoader/Scripts/Sync/Loader/LoaderManager.cs