EasyLoader: Wing.Tools.EaseLoader.RuntimeLoader Class Reference
Wing.Tools.EaseLoader.RuntimeLoader Class Reference
Public Member Functions
override string[] GetSchame ()
override string GetName ()
override ResponseData LoadSync (LoadContext context)
not support in webgl
Public Member Functions inherited from Wing.Tools.EaseLoader.BaseLoader
abstract string[] GetSchame ()
abstract string GetName ()
void Kill (LoadContext context, bool triggerCompleted=false)
stop load (useless in async mode)
void Load (LoadContext context)
virtual ResponseData LoadSync (LoadContext context)
string[] GetSchame ()
string GetName ()
void Load (LoadContext context)
void Kill (LoadContext context, bool triggerCompleted=false)
stop load (useless in async mode)
ResponseData LoadSync (LoadContext context)
Protected Member Functions
virtual UnityWebRequest CreateRequest (LoadContext context)
virtual ResponseData GetResponse (LoadContext context, UnityWebRequest request)
virtual void OnRequestEnd (UnityWebRequest request, LoadContext context)
virtual int RetryTimes (LoadContext context)
virtual bool WillRetry (LoadContext contenxt)
IEnumerator Request (UnityWebRequest request, LoadContext context)
override void OnLoad (LoadContext context)
virtual void OnLoad (LoadContext context)
Properties
static string name [get]
Properties inherited from Wing.Tools.EaseLoader.BaseLoader
LoadProgressEventHandler onProgress [get, set]
LoadCompletedEventHandler onCompleted [get, set]
Properties inherited from Wing.Tools.EaseLoader.ILoader
LoadProgressEventHandler onProgress [get, set]
LoadCompletedEventHandler onCompleted [get, set]
Member Function Documentation
CreateRequest()
virtual UnityWebRequest Wing.Tools.EaseLoader.RuntimeLoader.CreateRequest (LoadContext context) protected virtual
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
References Wing.Tools.EaseLoader.LoadContext.cacheType, Wing.Tools.EaseLoader.DefaultSettings.defaultCertificateHandler, Wing.Tools.EaseLoader.LoadContext.realUrl, Wing.Tools.EaseLoader.LoadContext.resourceType, Wing.Tools.EaseLoader.RuntimeLoader.RetryTimes(), and Wing.Tools.EaseLoader.LoadContext.timeout.
GetName()
override string Wing.Tools.EaseLoader.RuntimeLoader.GetName () virtual
Implements Wing.Tools.EaseLoader.BaseLoader.
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
References Wing.Tools.EaseLoader.RuntimeLoader.name.
GetResponse()
virtual ResponseData Wing.Tools.EaseLoader.RuntimeLoader.GetResponse (LoadContext context, UnityWebRequest request) protected virtual
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
References Wing.Tools.EaseLoader.AssetBundle, Wing.Tools.EaseLoader.LoadContext.cacheType, Wing.Tools.EaseLoader.Utils.CheckError(), Wing.Tools.EaseLoader.Utils.GetCacheInfo(), Wing.Tools.EaseLoader.Utils.GetMemorySize(), Wing.Tools.EaseLoader.LoadContext.key, Wing.Tools.EaseLoader.LoadContext.realUrl, Wing.Tools.EaseLoader.LoadContext.resourceType, Wing.Tools.EaseLoader.LoadContext.textEncodeing, and Wing.Tools.EaseLoader.Texture2D.
GetSchame()
override string[] Wing.Tools.EaseLoader.RuntimeLoader.GetSchame () virtual
Implements Wing.Tools.EaseLoader.BaseLoader.
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
References Wing.Tools.EaseLoader.RuntimeLoadContext.schame.
LoadSync()
override ResponseData Wing.Tools.EaseLoader.RuntimeLoader.LoadSync (LoadContext context) virtual
not support in webgl
Parameters
context
Returns
Reimplemented from Wing.Tools.EaseLoader.BaseLoader.
References Wing.Tools.EaseLoader.RuntimeLoader.CreateRequest(), Wing.Tools.EaseLoader.RuntimeLoader.GetResponse(), Wing.Tools.MonoSingleton< T >.Instance, Wing.Tools.EaseLoader.RuntimeLoader.LoadSync(), Wing.Tools.EaseLoader.RuntimeLoader.Request(), Wing.Tools.EaseLoader.LoadContext.timeout, and Wing.Tools.EaseLoader.RuntimeLoader.WillRetry().
OnLoad()
override void Wing.Tools.EaseLoader.RuntimeLoader.OnLoad (LoadContext context) protected virtual
Reimplemented from Wing.Tools.EaseLoader.BaseLoader.
OnRequestEnd()
virtual void Wing.Tools.EaseLoader.RuntimeLoader.OnRequestEnd (UnityWebRequest request, LoadContext context) protected virtual
Request()
IEnumerator Wing.Tools.EaseLoader.RuntimeLoader.Request (UnityWebRequest request, LoadContext context) protected
References Wing.Tools.EaseLoader.ResponseData.code, Wing.Tools.EaseLoader.RuntimeLoader.GetResponse(), Wing.Tools.MonoSingleton< T >.Instance, Wing.Tools.EaseLoader.LoadContext.key, Wing.Tools.EaseLoader.BaseLoader.onCompleted, Wing.Tools.EaseLoader.BaseLoader.onProgress, Wing.Tools.EaseLoader.RuntimeLoader.OnRequestEnd(), Wing.Tools.EaseLoader.ResponseData.status, and Wing.Tools.EaseLoader.RuntimeLoader.WillRetry().
RetryTimes()
virtual int Wing.Tools.EaseLoader.RuntimeLoader.RetryTimes (LoadContext context) protected virtual
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
WillRetry()
virtual bool Wing.Tools.EaseLoader.RuntimeLoader.WillRetry (LoadContext contenxt) protected virtual
Reimplemented in Wing.Tools.EaseLoader.WebLoader.
Property Documentation
name
string Wing.Tools.EaseLoader.RuntimeLoader.name static get
The documentation for this class was generated from the following files:
EaseLoader/Scripts/Loader/RuntimeLoader.cs
EaseLoader/Scripts/Sync/Loader/RuntimeLoader.cs