EasyLoader: Wing.Tools.EaseLoader.ResourceManager Class Reference
Wing.Tools.EaseLoader.ResourceManager Class Reference
easy load asset from Editor/Bundle/Player mode manager all assets in mapper.json when open USE_BUNDLE
Public Member Functions
void Initial (string mainAbName=null, Action< bool > done=null, LoaderTrigger trigger=null)
initial resource manager
void Reset (bool unloadedLoadedObject=false)
List< string > GetFilesInGroup (string groupName)
only support in uniform file name
void LoadAsset< T > (string path, Action< T > done, LoaderTrigger trigger=null)
load asset by full path or uniform url(when generate mapper.json must enable uniform url)
void LoadAsset (string path, Type assetType, Action< object > done, LoaderTrigger trigger=null)
void LoadAsset (string group, string name, Type assetType, Action< object > done, LoaderTrigger trigger=null)
void LoadAsset< T > (string group, string name, Action< T > done, LoaderTrigger trigger=null)
load asset by group and name
void LoadAssetR< T > (string group, string name, Action< ReferenceObject > done, LoaderTrigger trigger=null)
void LoadAssetF (string path, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger=null)
load asset from full path
bool ContainsUniqueName (string name)
void LoadAssetG (string group, string name, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger=null)
load asset by group
void LoadAssetBundle (string name, Action< AssetBundle > done, bool main=false, LoaderTrigger trigger=null)
void LoadAssetBundleR (string name, Action< ReferenceData > done, bool main=false, LoaderTrigger trigger=null)
void LoadScene (string path, LoadSceneMode loadMode=LoadSceneMode.Single, Action< float > progress=null, Action< bool > done=null, bool unloadBundle=true, LoaderTrigger trigger=null)
void LoadScene (string group, string sceneName, LoadSceneMode loadMode=LoadSceneMode.Single, Action< float > progress=null, Action< bool > done=null, bool unloadBundle=true, LoaderTrigger trigger=null)
void UnloadScene (string sceneName)
void LoadSpriteFromAtlas (string atlasPath, string name, Action< Sprite > done, LoaderTrigger trigger=null)
void LoadSpriteFromAtlas (string atlasGroup, string atlasName, string name, Action< Sprite > done, LoaderTrigger trigger=null)
void LoadSpriteFromAtlasR (string atlasGroup, string atlasName, string name, Action< ReferenceData > done, LoaderTrigger trigger=null)
loaded sprite from sprite atlas, return by reference data
void UnloadAssetF (string path, string atlasSpriteName=null)
unload asset by full path
void UnloadAsset (string group, string name, string atlasSpriteName=null)
will unload unused asset and remove it from memory cache
void UnloadAssetBundle (string name, bool unloadedLoadedObject=false)
unload assetbundle by name
void UnloadAllAssetBundle (bool unloadedLoadedObject=false)
unload all assetbunlde
void UnloadAll (bool unloadedLoadedObject=false)
unload all assetbundle and clear memory cache
void ABPreload (string[] abNames, Action< float > progress=null, Action< AssetBundle > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
preload assetbundle and relative assetbundles
void ABPreloadR (string[] abNames, Action< float > progress=null, Action< ReferenceData > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
preload assetbundle and relative assetbundles return refrence data
void Preload (Dictionary< string, EResourceType > assets, Action< float > progress=null, Action< object > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
void PreloadR (Dictionary< string, EResourceType > assets, Action< float > progress=null, Action< ReferenceData > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
bool InitialSync (string mainAbName=null)
T LoadAssetSync< T > (string path)
object LoadAssetSync (string path, Type assetType)
object LoadAssetSync (string group, string name, Type assetType)
T LoadAssetSync< T > (string group, string name)
ReferenceObject LoadAssetRSync< T > (string group, string name)
ReferenceObject LoadAssetFSync (string path, Type assetType)
ReferenceObject LoadAssetGSync (string group, string name, Type assetType)
AssetBundle LoadAssetBundleSync (string name, bool main=false)
ReferenceData LoadAssetBundleRSync (string name, bool main=false)
Sprite LoadSpriteFromAtlasSync (string atlasPath, string name)
Sprite LoadSpriteFromAtlasSync (string atlasGroup, string atlasName, string name)
ReferenceData LoadSpriteFromAtlasRSync (string atlasGroup, string atlasName, string name)
ReferenceData LoadSpriteFromAtlasSyncR (string atlasGroup, string atlasName, string name)
bool LoadSceneSync (string scenePath, LoadSceneMode loadMode=LoadSceneMode.Single, bool unloadBundle=true)
bool LoadSceneSync (string group, string sceneName, LoadSceneMode loadMode=LoadSceneMode.Single, bool unloadBundle=true)
Public Member Functions inherited from Wing.Tools.MonoSingleton< ResourceManager >
virtual void Initial ()
Public Attributes
string assetbundleExt = ".ab"
string abFileRelativeDir = "assetbundles/"
in editor mode: relative on streamingasset dir in player mode: relative on persistentData dir in player fallback mode: relative on streamingasset dir
string assetBaseUrl = ""
when use bundle,define where the ab file load from: streamingAssetPath/persistentDataPath/web url(start with http:// or https:// or relative url in webgl player)
ABDecryptHandler abDecryptHandler = Utils.DefaultABDecrypt
Additional Inherited Members
Static Protected Attributes inherited from Wing.Tools.MonoSingleton< ResourceManager >
static bool s_bEnableAutoCreate
static T s_pInstance
Properties inherited from Wing.Tools.MonoSingleton< ResourceManager >
static T Instance [get]
Detailed Description
easy load asset from Editor/Bundle/Player mode manager all assets in mapper.json when open USE_BUNDLE
if you want use async mode in webgl, please preload resources first
Member Function Documentation
ABPreload()
void Wing.Tools.EaseLoader.ResourceManager.ABPreload (string[] abNames, Action< float > progress = null, Action< AssetBundle > itemLoaded = null, Action done = null, LoaderTrigger trigger = null)
preload assetbundle and relative assetbundles
Parameters
abNames assetbundle names
progress progress invoke
itemLoaded on single assetbundle loaded
done all assetbundles loaded
References Wing.Tools.EaseLoader.AssetBundle.
ABPreloadR()
void Wing.Tools.EaseLoader.ResourceManager.ABPreloadR (string[] abNames, Action< float > progress = null, Action< ReferenceData > itemLoaded = null, Action done = null, LoaderTrigger trigger = null)
preload assetbundle and relative assetbundles return refrence data
Parameters
abNames assetbundle names
progress progress invoke
itemLoaded on single assetbundle loaded
done all assetbundles loaded
ContainsUniqueName()
bool Wing.Tools.EaseLoader.ResourceManager.ContainsUniqueName (string name)
GetFilesInGroup()
List< string > Wing.Tools.EaseLoader.ResourceManager.GetFilesInGroup (string groupName)
only support in uniform file name
Parameters
groupName
Returns
Initial()
void Wing.Tools.EaseLoader.ResourceManager.Initial (string mainAbName = null, Action< bool > done = null, LoaderTrigger trigger = null)
initial resource manager
Parameters
mainAbName main asset bundle name
done
InitialSync()
bool Wing.Tools.EaseLoader.ResourceManager.InitialSync (string mainAbName = null)
References Wing.Tools.MonoSingleton< T >.Instance, Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleSync(), and Wing.Tools.EaseLoader.ResourceManager.UnloadAssetBundle().
LoadAsset() [1/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadAsset (string group, string name, Type assetType, Action< object > done, LoaderTrigger trigger = null)
LoadAsset() [2/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadAsset (string path, Type assetType, Action< object > done, LoaderTrigger trigger = null)
LoadAsset< T >() [1/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadAsset< T > (string group, string name, Action< T > done, LoaderTrigger trigger = null)
load asset by group and name
Parameters
group
name
done
Template Parameters
T
Type Constraints
T : UnityEngine.Object
LoadAsset< T >() [2/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadAsset< T > (string path, Action< T > done, LoaderTrigger trigger = null)
load asset by full path or uniform url(when generate mapper.json must enable uniform url)
Parameters
path
done
Template Parameters
T
Type Constraints
T : UnityEngine.Object
LoadAssetBundle()
void Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundle (string name, Action< AssetBundle > done, bool main = false, LoaderTrigger trigger = null)
References Wing.Tools.EaseLoader.AssetBundle.
LoadAssetBundleR()
void Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleR (string name, Action< ReferenceData > done, bool main = false, LoaderTrigger trigger = null)
References Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.RuntimeLoadContext.KEY_DecryptFunction.
LoadAssetBundleRSync()
ReferenceData Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleRSync (string name, bool main = false)
References Wing.Tools.EaseLoader.AssetBundle, Wing.Tools.EaseLoader.ResourceManager.assetbundleExt, Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.RuntimeLoadContext.KEY_DecryptFunction.
LoadAssetBundleSync()
AssetBundle Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleSync (string name, bool main = false)
References Wing.Tools.EaseLoader.AssetBundle, Wing.Tools.EaseLoader.ReferenceObject.data, and Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleRSync().
LoadAssetF()
void Wing.Tools.EaseLoader.ResourceManager.LoadAssetF (string path, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger = null)
load asset from full path
Parameters
path full path in editor
assetType
done
LoadAssetFSync()
ReferenceObject Wing.Tools.EaseLoader.ResourceManager.LoadAssetFSync (string path, Type assetType)
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync().
LoadAssetG()
void Wing.Tools.EaseLoader.ResourceManager.LoadAssetG (string group, string name, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger = null)
load asset by group
Parameters
group
name
assetType
done
Exceptions
Exception
LoadAssetGSync()
ReferenceObject Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync (string group, string name, Type assetType)
LoadAssetR< T >()
void Wing.Tools.EaseLoader.ResourceManager.LoadAssetR< T > (string group, string name, Action< ReferenceObject > done, LoaderTrigger trigger = null)
Type Constraints
T : UnityEngine.Object
LoadAssetRSync< T >()
ReferenceObject Wing.Tools.EaseLoader.ResourceManager.LoadAssetRSync< T > (string group, string name)
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync().
LoadAssetSync() [1/2]
object Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync (string group, string name, Type assetType)
References Wing.Tools.EaseLoader.ReferenceObject.data, and Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync().
LoadAssetSync() [2/2]
object Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync (string path, Type assetType)
References Wing.Tools.EaseLoader.ReferenceObject.data, and Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync().
LoadAssetSync< T >() [1/2]
T Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync< T > (string group, string name)
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ReferenceObject.data, and Wing.Tools.EaseLoader.ResourceManager.LoadAssetRSync< T >().
LoadAssetSync< T >() [2/2]
T Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync< T > (string path)
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync< T >().
LoadScene() [1/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadScene (string group, string sceneName, LoadSceneMode loadMode = LoadSceneMode.Single, Action< float > progress = null, Action< bool > done = null, bool unloadBundle = true, LoaderTrigger trigger = null)
LoadScene() [2/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadScene (string path, LoadSceneMode loadMode = LoadSceneMode.Single, Action< float > progress = null, Action< bool > done = null, bool unloadBundle = true, LoaderTrigger trigger = null)
LoadSceneSync() [1/2]
bool Wing.Tools.EaseLoader.ResourceManager.LoadSceneSync (string group, string sceneName, LoadSceneMode loadMode = LoadSceneMode.Single, bool unloadBundle = true)
LoadSceneSync() [2/2]
bool Wing.Tools.EaseLoader.ResourceManager.LoadSceneSync (string scenePath, LoadSceneMode loadMode = LoadSceneMode.Single, bool unloadBundle = true)
LoadSpriteFromAtlas() [1/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlas (string atlasGroup, string atlasName, string name, Action< Sprite > done, LoaderTrigger trigger = null)
LoadSpriteFromAtlas() [2/2]
void Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlas (string atlasPath, string name, Action< Sprite > done, LoaderTrigger trigger = null)
LoadSpriteFromAtlasR()
void Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasR (string atlasGroup, string atlasName, string name, Action< ReferenceData > done, LoaderTrigger trigger = null)
loaded sprite from sprite atlas, return by reference data
Parameters
atlasGroup where atlas contain in package(asset bundle)
atlasName atlas name in asset manager
name sprite name
done
References Wing.Tools.MonoSingleton< T >.Instance.
LoadSpriteFromAtlasRSync()
ReferenceData Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasRSync (string atlasGroup, string atlasName, string name)
References Wing.Tools.MonoSingleton< T >.Instance.
LoadSpriteFromAtlasSync() [1/2]
Sprite Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSync (string atlasGroup, string atlasName, string name)
LoadSpriteFromAtlasSync() [2/2]
Sprite Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSync (string atlasPath, string name)
LoadSpriteFromAtlasSyncR()
ReferenceData Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSyncR (string atlasGroup, string atlasName, string name)
Preload()
void Wing.Tools.EaseLoader.ResourceManager.Preload (Dictionary< string, EResourceType > assets, Action< float > progress = null, Action< object > itemLoaded = null, Action done = null, LoaderTrigger trigger = null)
PreloadR()
void Wing.Tools.EaseLoader.ResourceManager.PreloadR (Dictionary< string, EResourceType > assets, Action< float > progress = null, Action< ReferenceData > itemLoaded = null, Action done = null, LoaderTrigger trigger = null)
Reset()
void Wing.Tools.EaseLoader.ResourceManager.Reset (bool unloadedLoadedObject = false)
References Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.ResourceManager.UnloadAll().
UnloadAll()
void Wing.Tools.EaseLoader.ResourceManager.UnloadAll (bool unloadedLoadedObject = false)
unload all assetbundle and clear memory cache
References Wing.Tools.MonoSingleton< T >.Instance.
UnloadAllAssetBundle()
void Wing.Tools.EaseLoader.ResourceManager.UnloadAllAssetBundle (bool unloadedLoadedObject = false)
unload all assetbunlde
Parameters
unloadedLoadedObject
References Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.Resources.
UnloadAsset()
void Wing.Tools.EaseLoader.ResourceManager.UnloadAsset (string group, string name, string atlasSpriteName = null)
will unload unused asset and remove it from memory cache
Parameters
group package name
name asset name
atlasSpriteName sprite name
References Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.Resources.
UnloadAssetBundle()
void Wing.Tools.EaseLoader.ResourceManager.UnloadAssetBundle (string name, bool unloadedLoadedObject = false)
unload assetbundle by name
Parameters
name
unloadedLoadedObject if true, will unload asset loaded
References Wing.Tools.MonoSingleton< T >.Instance, and Wing.Tools.EaseLoader.Resources.
UnloadAssetF()
void Wing.Tools.EaseLoader.ResourceManager.UnloadAssetF (string path, string atlasSpriteName = null)
unload asset by full path
Parameters
path full path
atlasSpriteName
UnloadScene()
void Wing.Tools.EaseLoader.ResourceManager.UnloadScene (string sceneName)
References Wing.Tools.EaseLoader.Resources.
Member Data Documentation
abDecryptHandler
ABDecryptHandler Wing.Tools.EaseLoader.ResourceManager.abDecryptHandler = Utils.DefaultABDecrypt
abFileRelativeDir
string Wing.Tools.EaseLoader.ResourceManager.abFileRelativeDir = "assetbundles/"
in editor mode: relative on streamingasset dir in player mode: relative on persistentData dir in player fallback mode: relative on streamingasset dir
assetBaseUrl
string Wing.Tools.EaseLoader.ResourceManager.assetBaseUrl = ""
when use bundle,define where the ab file load from: streamingAssetPath/persistentDataPath/web url(start with http:// or https:// or relative url in webgl player)
assetbundleExt
string Wing.Tools.EaseLoader.ResourceManager.assetbundleExt = ".ab"
The documentation for this class was generated from the following files:
EaseLoader/Scripts/ResourceManager.cs
EaseLoader/Scripts/Sync/ResourceManager.cs