EasyLoader: Wing.Tools.EaseLoader.Utils Class Reference
Wing.Tools.EaseLoader.Utils Class Reference
Static Public Member Functions
static string GetDataPath ()
static Texture2D LoadPNGFromDisk (string url)
static string StringMD5 (string data)
static int GetFileSize (string filePath)
static string GetFileHash (string filePath)
static int ConvertDateTimeInt (this System.DateTime time)
static DateTime ConvertIntDatetime (double utc)
static float[] ConvertByteToFloat (byte[] array)
static float ByteToM (long size)
static long GetMemorySize (object data)
static bool CheckUrl (string url)
static bool CheckError (UnityWebRequest req)
static CacheInfo GetCacheInfo (UnityWebRequest webRequest)
static int GetExpires (UnityWebRequest webRequest)
static string GetHttpFullRequestUrl (string url, Dictionary< string, object > query)
static string GetRequestPrefix (string url)
static ERequestFrom GetRequestType (string url)
static ECacheType ConvertToCacheType (ESourceType souceType)
static ESourceType ConvertToSourceType (ECacheType cacheType)
static Type ConvertAssetType (EResourceType resouceType)
static EResourceType ConvertResourceType (Type assetType)
static int CopyFolder (string sourceFolder, string destFolder, string addExtension=null, string[] excepts=null, Action< string, string > copyFunc=null)
复制文件夹及文件
static void RemoveFolder (string destFolder, bool removeRoot=true)
static byte[] DefaultABEncrypt (byte[] data, byte key)
static byte[] DefaultABDecrypt (byte[] data)
Properties
static string WWWStreamAssetsPath [get]
static string streamingAssetsPath [get]
static string defaultSchame [get]
Member Function Documentation
ByteToM()
static float Wing.Tools.EaseLoader.Utils.ByteToM (long size) static
CheckError()
static bool Wing.Tools.EaseLoader.Utils.CheckError (UnityWebRequest req) static
CheckUrl()
static bool Wing.Tools.EaseLoader.Utils.CheckUrl (string url) static
ConvertAssetType()
static Type Wing.Tools.EaseLoader.Utils.ConvertAssetType (EResourceType resouceType) static
References Wing.Tools.EaseLoader.AssetBundle, Wing.Tools.EaseLoader.AudioClip, and Wing.Tools.EaseLoader.Texture2D.
ConvertByteToFloat()
static float[] Wing.Tools.EaseLoader.Utils.ConvertByteToFloat (byte[] array) static
ConvertDateTimeInt()
static int Wing.Tools.EaseLoader.Utils.ConvertDateTimeInt (this System.DateTime time) static
ConvertIntDatetime()
static DateTime Wing.Tools.EaseLoader.Utils.ConvertIntDatetime (double utc) static
ConvertResourceType()
static EResourceType Wing.Tools.EaseLoader.Utils.ConvertResourceType (Type assetType) static
References Wing.Tools.EaseLoader.AssetBundle, and Wing.Tools.EaseLoader.AudioClip.
ConvertToCacheType()
static ECacheType Wing.Tools.EaseLoader.Utils.ConvertToCacheType (ESourceType souceType) static
ConvertToSourceType()
static ESourceType Wing.Tools.EaseLoader.Utils.ConvertToSourceType (ECacheType cacheType) static
CopyFolder()
static int Wing.Tools.EaseLoader.Utils.CopyFolder (string sourceFolder, string destFolder, string addExtension = null, string[] excepts = null, Action< string, string > copyFunc = null) static
复制文件夹及文件
Parameters
sourceFolder 原文件路径
destFolder 目标文件路径
Returns
References Wing.Tools.EaseLoader.Utils.CopyFolder().
DefaultABDecrypt()
static byte[] Wing.Tools.EaseLoader.Utils.DefaultABDecrypt (byte[] data) static
DefaultABEncrypt()
static byte[] Wing.Tools.EaseLoader.Utils.DefaultABEncrypt (byte[] data, byte key) static
GetCacheInfo()
static CacheInfo Wing.Tools.EaseLoader.Utils.GetCacheInfo (UnityWebRequest webRequest) static
References Wing.Tools.EaseLoader.Utils.GetExpires().
GetDataPath()
static string Wing.Tools.EaseLoader.Utils.GetDataPath () static
GetExpires()
static int Wing.Tools.EaseLoader.Utils.GetExpires (UnityWebRequest webRequest) static
References Wing.Tools.EaseLoader.Utils.ConvertDateTimeInt(), and Wing.Tools.EaseLoader.DefaultSettings.defaultDiskExpireDay.
GetFileHash()
static string Wing.Tools.EaseLoader.Utils.GetFileHash (string filePath) static
GetFileSize()
static int Wing.Tools.EaseLoader.Utils.GetFileSize (string filePath) static
GetHttpFullRequestUrl()
static string Wing.Tools.EaseLoader.Utils.GetHttpFullRequestUrl (string url, Dictionary< string, object > query) static
GetMemorySize()
static long Wing.Tools.EaseLoader.Utils.GetMemorySize (object data) static
References Wing.Tools.EaseLoader.DefaultSettings.defaultEncoding.
GetRequestPrefix()
static string Wing.Tools.EaseLoader.Utils.GetRequestPrefix (string url) static
GetRequestType()
static ERequestFrom Wing.Tools.EaseLoader.Utils.GetRequestType (string url) static
References Wing.Tools.EaseLoader.Utils.GetRequestPrefix().
LoadPNGFromDisk()
static Texture2D Wing.Tools.EaseLoader.Utils.LoadPNGFromDisk (string url) static
References Wing.Tools.EaseLoader.Texture2D.
RemoveFolder()
static void Wing.Tools.EaseLoader.Utils.RemoveFolder (string destFolder, bool removeRoot = true) static
StringMD5()
static string Wing.Tools.EaseLoader.Utils.StringMD5 (string data) static
Property Documentation
defaultSchame
string Wing.Tools.EaseLoader.Utils.defaultSchame static get
streamingAssetsPath
string Wing.Tools.EaseLoader.Utils.streamingAssetsPath static get
WWWStreamAssetsPath
string Wing.Tools.EaseLoader.Utils.WWWStreamAssetsPath static get
The documentation for this class was generated from the following file:
EaseLoader/Scripts/Msic/Utils.cs