EasyLoader: Wing.Tools.EaseLoader.RM Class Reference
Wing.Tools.EaseLoader.RM Class Reference
Static Public Member Functions
static void Initial (string mainAbName=null, Action< bool > done=null, LoaderTrigger trigger=null)
static void Reset (bool unloadedLoadedObject=false)
static List< string > GetFilesInGroup (string groupName)
static void LoadAsset< T > (string path, Action< T > done, LoaderTrigger trigger=null)
static void LoadAsset (string path, Type assetType, Action< object > done, LoaderTrigger trigger=null)
static void LoadAsset (string group, string name, Type assetType, Action< object > done, LoaderTrigger trigger=null)
static void LoadAsset< T > (string group, string name, Action< T > done, LoaderTrigger trigger=null)
static void LoadAssetR< T > (string group, string name, Action< ReferenceObject > done, LoaderTrigger trigger=null)
static void LoadAssetF (string path, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger=null)
static bool ContainsUniqueName (string name)
static void LoadAssetG (string group, string name, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger=null)
static void LoadAssetBundle (string name, Action< AssetBundle > done, bool main=false, LoaderTrigger trigger=null)
static void LoadAssetBundleR (string name, Action< ReferenceData > done, bool main=false, LoaderTrigger trigger=null)
static void LoadScene (string path, LoadSceneMode loadMode=LoadSceneMode.Single, Action< float > progress=null, Action< bool > done=null, bool unloadBundle=true, LoaderTrigger trigger=null)
static void LoadScene (string group, string sceneName, LoadSceneMode loadMode=LoadSceneMode.Single, Action< float > progress=null, Action< bool > done=null, bool unloadBundle=true, LoaderTrigger trigger=null)
static void UnloadScene (string sceneName)
static void LoadSpriteFromAtlas (string atlasPath, string name, Action< Sprite > done, LoaderTrigger trigger=null)
static void LoadSpriteFromAtlas (string atlasGroup, string atlasName, string name, Action< Sprite > done, LoaderTrigger trigger=null)
static void LoadSpriteFromAtlasR (string atlasGroup, string atlasName, string name, Action< ReferenceData > done, LoaderTrigger trigger=null)
static void UnloadAssetF (string path, string atlasSpriteName=null)
static void UnloadAsset (string group, string name, string atlasSpriteName=null)
static void UnloadAssetBundle (string name, bool unloadedLoadedObject=false)
static void UnloadAllAssetBundle (bool unloadedLoadedObject=false)
static void UnloadAll (bool unloadedLoadedObject=false)
static void ABPreload (string[] abNames, Action< float > progress=null, Action< AssetBundle > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
static void ABPreloadR (string[] abNames, Action< float > progress=null, Action< ReferenceData > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
static void Preload (Dictionary< string, EResourceType > assets, Action< float > progress=null, Action< object > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
static void PreloadR (Dictionary< string, EResourceType > assets, Action< float > progress=null, Action< ReferenceData > itemLoaded=null, Action done=null, LoaderTrigger trigger=null)
static bool InitialSync (string mainAbName=null)
static T LoadAssetSync< T > (string path)
static object LoadAssetSync (string path, Type assetType)
static object LoadAssetSync (string group, string name, Type assetType)
static T LoadAssetSync< T > (string group, string name)
static ReferenceObject LoadAssetRSync< T > (string group, string name)
static ReferenceObject LoadAssetFSync (string path, Type assetType)
static ReferenceObject LoadAssetGSync (string group, string name, Type assetType)
static AssetBundle LoadAssetBundleSync (string name, bool main=false)
static ReferenceData LoadAssetBundleRSync (string name, bool main=false)
static Sprite LoadSpriteFromAtlasSync (string atlasPath, string name)
static Sprite LoadSpriteFromAtlasSync (string atlasGroup, string atlasName, string name)
static ReferenceData LoadSpriteFromAtlasRSync (string atlasGroup, string atlasName, string name)
static ReferenceData LoadSpriteFromAtlasSyncR (string atlasGroup, string atlasName, string name)
static bool LoadSceneSync (string scenePath, LoadSceneMode loadMode=LoadSceneMode.Single, bool unloadBundle=true)
static bool LoadSceneSync (string group, string sceneName, LoadSceneMode loadMode=LoadSceneMode.Single, bool unloadBundle=true)
Properties
static string assetbundleExt [get, set]
static string abFileRelativeDir [get, set]
static string assetBaseUrl [get, set]
static ABDecryptHandler abDecryptHandler [get, set]
Member Function Documentation
ABPreload()
static void Wing.Tools.EaseLoader.RM.ABPreload (string[] abNames, Action< float > progress = null, Action< AssetBundle > itemLoaded = null, Action done = null, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.ABPreload().
ABPreloadR()
static void Wing.Tools.EaseLoader.RM.ABPreloadR (string[] abNames, Action< float > progress = null, Action< ReferenceData > itemLoaded = null, Action done = null, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.ABPreloadR().
ContainsUniqueName()
static bool Wing.Tools.EaseLoader.RM.ContainsUniqueName (string name) static
References Wing.Tools.EaseLoader.ResourceManager.ContainsUniqueName().
GetFilesInGroup()
static List< string > Wing.Tools.EaseLoader.RM.GetFilesInGroup (string groupName) static
References Wing.Tools.EaseLoader.ResourceManager.GetFilesInGroup().
Initial()
static void Wing.Tools.EaseLoader.RM.Initial (string mainAbName = null, Action< bool > done = null, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.Initial().
InitialSync()
static bool Wing.Tools.EaseLoader.RM.InitialSync (string mainAbName = null) static
References Wing.Tools.EaseLoader.ResourceManager.InitialSync().
LoadAsset() [1/2]
static void Wing.Tools.EaseLoader.RM.LoadAsset (string group, string name, Type assetType, Action< object > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAsset().
LoadAsset() [2/2]
static void Wing.Tools.EaseLoader.RM.LoadAsset (string path, Type assetType, Action< object > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAsset().
LoadAsset< T >() [1/2]
static void Wing.Tools.EaseLoader.RM.LoadAsset< T > (string group, string name, Action< T > done, LoaderTrigger trigger = null) static
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAsset().
LoadAsset< T >() [2/2]
static void Wing.Tools.EaseLoader.RM.LoadAsset< T > (string path, Action< T > done, LoaderTrigger trigger = null) static
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAsset().
LoadAssetBundle()
static void Wing.Tools.EaseLoader.RM.LoadAssetBundle (string name, Action< AssetBundle > done, bool main = false, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundle().
LoadAssetBundleR()
static void Wing.Tools.EaseLoader.RM.LoadAssetBundleR (string name, Action< ReferenceData > done, bool main = false, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleR().
LoadAssetBundleRSync()
static ReferenceData Wing.Tools.EaseLoader.RM.LoadAssetBundleRSync (string name, bool main = false) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleRSync().
LoadAssetBundleSync()
static AssetBundle Wing.Tools.EaseLoader.RM.LoadAssetBundleSync (string name, bool main = false) static
References Wing.Tools.EaseLoader.AssetBundle, and Wing.Tools.EaseLoader.ResourceManager.LoadAssetBundleSync().
LoadAssetF()
static void Wing.Tools.EaseLoader.RM.LoadAssetF (string path, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetF().
LoadAssetFSync()
static ReferenceObject Wing.Tools.EaseLoader.RM.LoadAssetFSync (string path, Type assetType) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetFSync().
LoadAssetG()
static void Wing.Tools.EaseLoader.RM.LoadAssetG (string group, string name, Type assetType, Action< ReferenceObject > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetG().
LoadAssetGSync()
static ReferenceObject Wing.Tools.EaseLoader.RM.LoadAssetGSync (string group, string name, Type assetType) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetGSync().
LoadAssetR< T >()
static void Wing.Tools.EaseLoader.RM.LoadAssetR< T > (string group, string name, Action< ReferenceObject > done, LoaderTrigger trigger = null) static
Type Constraints
T : UnityEngine.Object
LoadAssetRSync< T >()
static ReferenceObject Wing.Tools.EaseLoader.RM.LoadAssetRSync< T > (string group, string name) static
Type Constraints
T : UnityEngine.Object
LoadAssetSync() [1/2]
static object Wing.Tools.EaseLoader.RM.LoadAssetSync (string group, string name, Type assetType) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync().
LoadAssetSync() [2/2]
static object Wing.Tools.EaseLoader.RM.LoadAssetSync (string path, Type assetType) static
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync().
LoadAssetSync< T >() [1/2]
static T Wing.Tools.EaseLoader.RM.LoadAssetSync< T > (string group, string name) static
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync().
LoadAssetSync< T >() [2/2]
static T Wing.Tools.EaseLoader.RM.LoadAssetSync< T > (string path) static
Type Constraints
T : UnityEngine.Object
References Wing.Tools.EaseLoader.ResourceManager.LoadAssetSync().
LoadScene() [1/2]
static void Wing.Tools.EaseLoader.RM.LoadScene (string group, string sceneName, LoadSceneMode loadMode = LoadSceneMode.Single, Action< float > progress = null, Action< bool > done = null, bool unloadBundle = true, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadScene().
LoadScene() [2/2]
static void Wing.Tools.EaseLoader.RM.LoadScene (string path, LoadSceneMode loadMode = LoadSceneMode.Single, Action< float > progress = null, Action< bool > done = null, bool unloadBundle = true, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadScene().
LoadSceneSync() [1/2]
static bool Wing.Tools.EaseLoader.RM.LoadSceneSync (string group, string sceneName, LoadSceneMode loadMode = LoadSceneMode.Single, bool unloadBundle = true) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSceneSync().
LoadSceneSync() [2/2]
static bool Wing.Tools.EaseLoader.RM.LoadSceneSync (string scenePath, LoadSceneMode loadMode = LoadSceneMode.Single, bool unloadBundle = true) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSceneSync().
LoadSpriteFromAtlas() [1/2]
static void Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlas (string atlasGroup, string atlasName, string name, Action< Sprite > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlas().
LoadSpriteFromAtlas() [2/2]
static void Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlas (string atlasPath, string name, Action< Sprite > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlas().
LoadSpriteFromAtlasR()
static void Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlasR (string atlasGroup, string atlasName, string name, Action< ReferenceData > done, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasR().
LoadSpriteFromAtlasRSync()
static ReferenceData Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlasRSync (string atlasGroup, string atlasName, string name) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasRSync().
LoadSpriteFromAtlasSync() [1/2]
static Sprite Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlasSync (string atlasGroup, string atlasName, string name) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSync().
LoadSpriteFromAtlasSync() [2/2]
static Sprite Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlasSync (string atlasPath, string name) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSync().
LoadSpriteFromAtlasSyncR()
static ReferenceData Wing.Tools.EaseLoader.RM.LoadSpriteFromAtlasSyncR (string atlasGroup, string atlasName, string name) static
References Wing.Tools.EaseLoader.ResourceManager.LoadSpriteFromAtlasSyncR().
Preload()
static void Wing.Tools.EaseLoader.RM.Preload (Dictionary< string, EResourceType > assets, Action< float > progress = null, Action< object > itemLoaded = null, Action done = null, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.Preload().
PreloadR()
static void Wing.Tools.EaseLoader.RM.PreloadR (Dictionary< string, EResourceType > assets, Action< float > progress = null, Action< ReferenceData > itemLoaded = null, Action done = null, LoaderTrigger trigger = null) static
References Wing.Tools.EaseLoader.ResourceManager.PreloadR().
Reset()
static void Wing.Tools.EaseLoader.RM.Reset (bool unloadedLoadedObject = false) static
References Wing.Tools.EaseLoader.ResourceManager.Reset().
UnloadAll()
static void Wing.Tools.EaseLoader.RM.UnloadAll (bool unloadedLoadedObject = false) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadAll().
UnloadAllAssetBundle()
static void Wing.Tools.EaseLoader.RM.UnloadAllAssetBundle (bool unloadedLoadedObject = false) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadAllAssetBundle().
UnloadAsset()
static void Wing.Tools.EaseLoader.RM.UnloadAsset (string group, string name, string atlasSpriteName = null) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadAsset().
UnloadAssetBundle()
static void Wing.Tools.EaseLoader.RM.UnloadAssetBundle (string name, bool unloadedLoadedObject = false) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadAssetBundle().
UnloadAssetF()
static void Wing.Tools.EaseLoader.RM.UnloadAssetF (string path, string atlasSpriteName = null) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadAssetF().
UnloadScene()
static void Wing.Tools.EaseLoader.RM.UnloadScene (string sceneName) static
References Wing.Tools.EaseLoader.ResourceManager.UnloadScene().
Property Documentation
abDecryptHandler
ABDecryptHandler Wing.Tools.EaseLoader.RM.abDecryptHandler static get set
abFileRelativeDir
string Wing.Tools.EaseLoader.RM.abFileRelativeDir static get set
assetBaseUrl
string Wing.Tools.EaseLoader.RM.assetBaseUrl static get set
assetbundleExt
string Wing.Tools.EaseLoader.RM.assetbundleExt static get set
The documentation for this class was generated from the following files:
EaseLoader/Scripts/RM.cs
EaseLoader/Scripts/Sync/RM.cs