EasyLoader: Wing.Tools.EaseLoader.CacherManager Class Reference
Wing.Tools.EaseLoader.CacherManager Class Reference
Public Member Functions
void Regist (ECacheType type, ICacher cacher)
ICacher GetCacher (ECacheType type)
ICacher StrictGet (ECacheType type)
bool IsCacher (ICacher cacher, ECacheType cacherType)
bool HasKey (string key, ECacheType cacherType=ECacheType.All)
bool IsInTime (string key, ECacheType cacherType=ECacheType.All)
bool IsInMemoryCache (string key)
ReferenceData MemoryCache (string key, object data, bool overwrite=true, ESourceType sourceType=ESourceType.None, string saveAs=null)
ReferenceData DiskCache (string key, object data, bool overwrite=true, ESourceType sourceType=ESourceType.None, string saveAs=null)
ReferenceData Cache (string key, object data, bool overwrite=true, ECacheType cacherType=ECacheType.All, ESourceType sourceType=ESourceType.None, string saveAs=null)
void Cache (string key, ReferenceData data, bool overwrite=true, ECacheType cacherType=ECacheType.All, ESourceType sourceType=ESourceType.None, Type targetType=null, string saveAs=null)
void GetData (string key, Action< ResponseData > done, ECacheType cacherType=ECacheType.All, Type targetType=null, LoaderTrigger trigger=null)
void Remove (string key, ECacheType cacherType=ECacheType.All)
void RemoveAll (ECacheType cacherType=ECacheType.All)
void Collect (bool all=false, bool checkCacheSize=true, DateTime? before=null, ECacheType cacherType=ECacheType.All)
long GetTotalCacheSize (ECacheType cacherType=ECacheType.Memory)
ResponseData GetDataSync (string key, ECacheType cacherType=ECacheType.All, Type targetType=null)
Public Member Functions inherited from Wing.Tools.MonoSingleton< CacherManager >
virtual void Initial ()
Properties
static Dictionary< Type, ISerializable > serializers [get]
HitStatistics statistics [get]
Properties inherited from Wing.Tools.MonoSingleton< CacherManager >
static T Instance [get]
Additional Inherited Members
Static Protected Attributes inherited from Wing.Tools.MonoSingleton< CacherManager >
static bool s_bEnableAutoCreate
static T s_pInstance
Member Function Documentation
Cache() [1/2]
ReferenceData Wing.Tools.EaseLoader.CacherManager.Cache (string key, object data, bool overwrite = true, ECacheType cacherType = ECacheType.All, ESourceType sourceType = ESourceType.None, string saveAs = null)
References Wing.Tools.EaseLoader.CacherManager.Cache(), Wing.Tools.EaseLoader.CacherManager.Remove(), and Wing.Tools.EaseLoader.CacherManager.serializers.
Cache() [2/2]
void Wing.Tools.EaseLoader.CacherManager.Cache (string key, ReferenceData data, bool overwrite = true, ECacheType cacherType = ECacheType.All, ESourceType sourceType = ESourceType.None, Type targetType = null, string saveAs = null)
References Wing.Tools.EaseLoader.ReferenceData.bytes, Wing.Tools.EaseLoader.Utils.ConvertToCacheType(), Wing.Tools.EaseLoader.ReferenceObject.data, Wing.Tools.EaseLoader.CacherManager.IsCacher(), Wing.Tools.EaseLoader.ReferenceData.memorySize, Wing.Tools.EaseLoader.CacherManager.Remove(), Wing.Tools.EaseLoader.CacherManager.serializers, and Wing.Tools.EaseLoader.ReferenceData.size.
Collect()
void Wing.Tools.EaseLoader.CacherManager.Collect (bool all = false, bool checkCacheSize = true, DateTime? before = null, ECacheType cacherType = ECacheType.All)
References Wing.Tools.EaseLoader.DefaultSettings.enableAutoCollect, and Wing.Tools.EaseLoader.CacherManager.IsCacher().
DiskCache()
ReferenceData Wing.Tools.EaseLoader.CacherManager.DiskCache (string key, object data, bool overwrite = true, ESourceType sourceType = ESourceType.None, string saveAs = null)
References Wing.Tools.EaseLoader.CacherManager.Cache().
GetCacher()
ICacher Wing.Tools.EaseLoader.CacherManager.GetCacher (ECacheType type)
GetData()
void Wing.Tools.EaseLoader.CacherManager.GetData (string key, Action< ResponseData > done, ECacheType cacherType = ECacheType.All, Type targetType = null, LoaderTrigger trigger = null)
References Wing.Tools.EaseLoader.Utils.ConvertToSourceType(), Wing.Tools.EaseLoader.CacherManager.IsCacher(), and Wing.Tools.EaseLoader.CacherManager.serializers.
GetDataSync()
ResponseData Wing.Tools.EaseLoader.CacherManager.GetDataSync (string key, ECacheType cacherType = ECacheType.All, Type targetType = null)
References Wing.Tools.EaseLoader.Utils.ConvertToSourceType(), Wing.Tools.EaseLoader.CacherManager.IsCacher(), and Wing.Tools.EaseLoader.CacherManager.serializers.
GetTotalCacheSize()
long Wing.Tools.EaseLoader.CacherManager.GetTotalCacheSize (ECacheType cacherType = ECacheType.Memory)
References Wing.Tools.EaseLoader.CacherManager.IsCacher().
HasKey()
bool Wing.Tools.EaseLoader.CacherManager.HasKey (string key, ECacheType cacherType = ECacheType.All)
References Wing.Tools.EaseLoader.CacherManager.IsCacher().
IsCacher()
bool Wing.Tools.EaseLoader.CacherManager.IsCacher (ICacher cacher, ECacheType cacherType)
References Wing.Tools.EaseLoader.ICacher.GetCacherType().
IsInMemoryCache()
bool Wing.Tools.EaseLoader.CacherManager.IsInMemoryCache (string key)
References Wing.Tools.EaseLoader.CacherManager.GetCacher().
IsInTime()
bool Wing.Tools.EaseLoader.CacherManager.IsInTime (string key, ECacheType cacherType = ECacheType.All)
References Wing.Tools.EaseLoader.CacherManager.IsCacher().
MemoryCache()
ReferenceData Wing.Tools.EaseLoader.CacherManager.MemoryCache (string key, object data, bool overwrite = true, ESourceType sourceType = ESourceType.None, string saveAs = null)
References Wing.Tools.EaseLoader.CacherManager.Cache().
Regist()
void Wing.Tools.EaseLoader.CacherManager.Regist (ECacheType type, ICacher cacher)
Remove()
void Wing.Tools.EaseLoader.CacherManager.Remove (string key, ECacheType cacherType = ECacheType.All)
References Wing.Tools.EaseLoader.CacherManager.IsCacher().
RemoveAll()
void Wing.Tools.EaseLoader.CacherManager.RemoveAll (ECacheType cacherType = ECacheType.All)
References Wing.Tools.EaseLoader.CacherManager.IsCacher().
StrictGet()
ICacher Wing.Tools.EaseLoader.CacherManager.StrictGet (ECacheType type)
References Wing.Tools.EaseLoader.CacherManager.GetCacher().
Property Documentation
serializers
Dictionary<Type, ISerializable> Wing.Tools.EaseLoader.CacherManager.serializers static get
statistics
HitStatistics Wing.Tools.EaseLoader.CacherManager.statistics get
The documentation for this class was generated from the following files:
EaseLoader/Scripts/Cacher/CacherManager.cs
EaseLoader/Scripts/Sync/Cacher/CacherManager.cs