EasyLoader: Wing.Tools.EaseLoader.MemoryCacher Class Reference
Wing.Tools.EaseLoader.MemoryCacher Class Reference
Public Member Functions
MemoryCacher ()
ECacheType GetCacherType ()
void Cache (string key, ReferenceData data, bool overwrite, string saveAs=null)
void Collect (bool all=false, bool checkCacheSize=true, DateTime? before=null)
collect the files out of dates
void Get (string key, Action< ReferenceData > done, LoaderTrigger trigger=null)
long GetTotalCacheSize ()
bool HasKey (string key)
bool IsInTime (string key)
int GetReferenceCount (string key)
void Remove (string key)
void RemoveAll ()
void Update ()
ReferenceData GetSync (string key)
ECacheType GetCacherType ()
bool HasKey (string key)
bool IsInTime (string key)
void Update ()
void Cache (string key, ReferenceData data, bool overwrite, string saveAs=null)
void Get (string key, Action< ReferenceData > done, LoaderTrigger trigger=null)
void Remove (string key)
void RemoveAll ()
void Collect (bool all=false, bool checkCacheSize=true, DateTime? before=null)
collect the files out of dates
long GetTotalCacheSize ()
ReferenceData GetSync (string key)
Properties
static ECacheType type [get]
int prority [get]
float autoGCTime [get, set]
in seconds，-1(lower than 0) means not auto gc,0 means gc per frame
long maxCacheSize [get, set]
bytes size in memory,shoud stagger the disk gc time，-1(lower than 0) means size not limit
Properties inherited from Wing.Tools.EaseLoader.ICacher
int prority [get]
float autoGCTime [get, set]
in seconds，-1(lower than 0) means not auto gc,0 means gc per frame
long maxCacheSize [get, set]
bytes size in memory,shoud stagger the disk gc time，-1(lower than 0) means size not limit
Constructor & Destructor Documentation
MemoryCacher()
Wing.Tools.EaseLoader.MemoryCacher.MemoryCacher ()
References Wing.Tools.EaseLoader.DefaultSettings.maxMemoryCacheSize, and Wing.Tools.EaseLoader.DefaultSettings.memoryAutoGCTime.
Member Function Documentation
Cache()
void Wing.Tools.EaseLoader.MemoryCacher.Cache (string key, ReferenceData data, bool overwrite, string saveAs = null)
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.EaseLoader.MemoryCacher.Remove().
Collect()
void Wing.Tools.EaseLoader.MemoryCacher.Collect (bool all = false, bool checkCacheSize = true, DateTime? before = null)
collect the files out of dates
Parameters
all delete all unlocked cached files
checkCacheSize delete files by check total size
before delete cache data before this time,deault is null and not check expires time
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.EaseLoader.Utils.ByteToM(), Wing.Tools.EaseLoader.Utils.ConvertDateTimeInt(), Wing.Tools.EaseLoader.MemoryCacher.GetTotalCacheSize(), Wing.Tools.EaseLoader.Resources, and Wing.Tools.EaseLoader.DefaultSettings.showDebugInfo.
Get()
void Wing.Tools.EaseLoader.MemoryCacher.Get (string key, Action< ReferenceData > done, LoaderTrigger trigger = null)
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.MonoSingleton< T >.Instance.
GetCacherType()
ECacheType Wing.Tools.EaseLoader.MemoryCacher.GetCacherType ()
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.EaseLoader.MemoryCacher.type.
GetReferenceCount()
int Wing.Tools.EaseLoader.MemoryCacher.GetReferenceCount (string key)
GetSync()
ReferenceData Wing.Tools.EaseLoader.MemoryCacher.GetSync (string key)
Implements Wing.Tools.EaseLoader.ICacher.
GetTotalCacheSize()
long Wing.Tools.EaseLoader.MemoryCacher.GetTotalCacheSize ()
Implements Wing.Tools.EaseLoader.ICacher.
HasKey()
bool Wing.Tools.EaseLoader.MemoryCacher.HasKey (string key)
Implements Wing.Tools.EaseLoader.ICacher.
IsInTime()
bool Wing.Tools.EaseLoader.MemoryCacher.IsInTime (string key)
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.EaseLoader.Utils.ConvertDateTimeInt(), and Wing.Tools.EaseLoader.MemoryCacher.HasKey().
Remove()
void Wing.Tools.EaseLoader.MemoryCacher.Remove (string key)
Implements Wing.Tools.EaseLoader.ICacher.
RemoveAll()
void Wing.Tools.EaseLoader.MemoryCacher.RemoveAll ()
Implements Wing.Tools.EaseLoader.ICacher.
Update()
void Wing.Tools.EaseLoader.MemoryCacher.Update ()
Implements Wing.Tools.EaseLoader.ICacher.
References Wing.Tools.EaseLoader.MemoryCacher.autoGCTime, Wing.Tools.EaseLoader.MemoryCacher.Collect(), Wing.Tools.EaseLoader.Timer.Elapsed, Wing.Tools.EaseLoader.DefaultSettings.enableAutoCollect, and Wing.Tools.EaseLoader.Timer.Start().
Property Documentation
autoGCTime
float Wing.Tools.EaseLoader.MemoryCacher.autoGCTime get set
in seconds，-1(lower than 0) means not auto gc,0 means gc per frame
Implements Wing.Tools.EaseLoader.ICacher.
maxCacheSize
long Wing.Tools.EaseLoader.MemoryCacher.maxCacheSize get set
bytes size in memory,shoud stagger the disk gc time，-1(lower than 0) means size not limit
Implements Wing.Tools.EaseLoader.ICacher.
prority
int Wing.Tools.EaseLoader.MemoryCacher.prority get
Implements Wing.Tools.EaseLoader.ICacher.
type
ECacheType Wing.Tools.EaseLoader.MemoryCacher.type static get
The documentation for this class was generated from the following files:
EaseLoader/Scripts/Cacher/MemoryCacher.cs
EaseLoader/Scripts/Sync/Cacher/MemoryCacher.cs