EasyLoader: Wing.Tools.EaseLoader.TaskLimiter Class Reference
Wing.Tools.EaseLoader.TaskLimiter Class Reference
Public Member Functions
void RemoveAll ()
void Remove (LoadContext context)
LoadTask CreateTask (ILoader loader, LoadContext context)
LoadTask Push (ILoader loader, LoadContext context)
void Update ()
Properties
int capacity [get, set]
Member Function Documentation
CreateTask()
LoadTask Wing.Tools.EaseLoader.TaskLimiter.CreateTask (ILoader loader, LoadContext context)
References Wing.Tools.EaseLoader.LoadTask.Init().
Push()
LoadTask Wing.Tools.EaseLoader.TaskLimiter.Push (ILoader loader, LoadContext context)
References Wing.Tools.EaseLoader.TaskLimiter.CreateTask().
Remove()
void Wing.Tools.EaseLoader.TaskLimiter.Remove (LoadContext context)
References Wing.Tools.EaseLoader.LoadTask.Reset().
RemoveAll()
void Wing.Tools.EaseLoader.TaskLimiter.RemoveAll ()
Update()
void Wing.Tools.EaseLoader.TaskLimiter.Update ()
References Wing.Tools.MonoSingleton< T >.Instance.
Property Documentation
capacity
int Wing.Tools.EaseLoader.TaskLimiter.capacity get set
The documentation for this class was generated from the following file:
EaseLoader/Scripts/Msic/TaskLimiter.cs